### PR TITLE
Use CommonMarker

### LINKED ISSUE #288: fix remaining markdown issues
- tildes for strikethrough don't work, because we have to pass `:strict` (see cbf14021ac06).
- `@username` expansion doesn't work, because of security issues (see 0f498d3ee3).

### PR DESCRIPTION
**Pull request by kivikakk**
Fixes #288. We add CommonMark compatibility, strikethrough, `@username` expansion (with a kinda awkward AST walk, but it's simple if verbose), and with any luck general malleability going forward.

### CODE REVIEW

File: extras/markdowner.rb [hunk 1]
```diff
@@ -7,49 +7,71 @@ def self.to_html(text, opts = {})
...
     end
 
+    if !opts[:allow_images]
+      ng.css("img").remove
+    end
+
     # make links have rel=nofollow
     ng.css("a").each do |h|
-      h[:rel] = "nofollow"
+      h[:rel] = "nofollow" unless h[:href].starts_with?("/")
```
Comment (jcs) [inline extras/markdowner.rb]: A link like `[test](//jcs.org/)` would fail that, but still need `nofollow`.

File: extras/markdowner.rb [hunk 2]
```diff
@@ -7,49 +7,71 @@ def self.to_html(text, opts = {})
...
+    node.each do |child|
+      walk_text_nodes(child, &block)
     end
-end
+  end
 
-    ng.at_css("body").inner_html
+  def self.postprocess_text_node(node)
+    while node
+      return unless node.string_content =~ /\B(@[\w\-]+)/
```
Comment (jcs) [inline extras/markdowner.rb]: It might be worth moving the username validation regex in `User` out to a constant and checking against that.

File: extras/markdowner.rb (hunk 1 above)
Comment (kivikakk) [inline extras/markdowner.rb]: Good catch. Now checking for a nil host on URI parse.

File: extras/markdowner.rb (hunk 2 above)
Comment (kivikakk) [inline extras/markdowner.rb]: :+1:

**Comment by jcs** [comment]
Thanks a lot for taking care of this!
